name: desktop_entry
description: Implementation of the freedesktop.org association between MIME types and applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  crypto: ^3.0.7
  dartx: ^1.2.0
  freedesktop_file_parser:
  path: ^1.9.1
  result:
  xdg_dir:
    version: ^1.0.1
    git:
      url: https://github.com/ross96D/xdg_dir.dart
      tag_pattern: "{{version}}"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
