name: xdg_mime
description: Implementation of the freedesktop.org Shared MIME-info Database specification for reading the MIME database.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

desktop_entry:
  path: packages/desktop_entry
freedesktop_file_parser:
  path: packages/freedesktop_file_parser
mime_apps:
  path: packages/mime_apps
mime_db:
  path: packages/mime_db
result:
  path: packages/result

workspace:
  - pkgs/result
  - pkgs/desktop_entry
  - pkgs/mime_db
  - pkgs/mime_apps
  - pkgs/freedesktop_file_parser
