name: xdg_mime
description: Implementation of the freedesktop.org Shared MIME-info Database specification for reading the MIME database.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - pkgs/mime_db
  - pkgs/mime_apps
  - pkgs/freedesktop_file_parser
