name: xdg_mime
description: Implementation of the freedesktop.org Shared MIME-info Database specification for reading the MIME database.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  desktop_entry:
    path: pkgs/desktop_entry
  freedesktop_file_parser:
    path: pkgs/freedesktop_file_parser
  xdg_mime_apps:
    path: pkgs/mime_apps
  xdg_mime_db:
    path: pkgs/mime_db
  result:
    path: pkgs/result

workspace:
  - pkgs/result
  - pkgs/desktop_entry
  - pkgs/mime_db
  - pkgs/mime_apps
  - pkgs/freedesktop_file_parser
