name: xdg_mime_apps
description: Implementation of the freedesktop.org association between MIME types and applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dartx: ^1.2.0

  xdg_dir:
    version: ^1.0.1
    git:
      url: https://github.com/ross96D/xdg_dir.dart
      tag_pattern: "{{version}}"

  result:
    path: ../result
  freedesktop_file_parser:
    path: ../freedesktop_file_parser

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
